name: TimeMine
version: 0.0.1
author: Github/popatop15
website: www.indicacorp.net
main: net.indicacorp.timemine.TimeMine
api-version: "1.14"
commands:
  timemine:
    description: TimeMine base command.
    usage: "/timemine help"
    aliases: [tm]